language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - "cd src/"
  # "pip install cython"
  #- "pip install numpy"
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy cython
  - conda install --yes python=$TRAVIS_PYTHON_VERSION -c https://conda.anaconda.org/chemreac sundials
  - "pip install -e ."
script:
  - "cd src/"
  - "python setup.py test"
