language: python
python:
  - "2.7"
apt:
  packages:
    - gfortran

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels https://conda.anaconda.org/chemreac
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - "cd src/"
  # "pip install cython"
  #- "pip install numpy"
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy cython sundials scipy matplotlib sympy
  - source activate test-environment
  - pip install -e . --install-option='--fcompiler=/usr/bin/gfortran'
script:
  - "cd src/"
  - "python setup.py test"
